In [1]:
!uv init

Initialized project `working`


In [2]:
!uv pip install --system  transformers datasets torch accelerate hf_xet

Using Python 3.11.11 environment at: /usr
Resolved 68 packages in 419ms                                        
⠙ Preparing packages... (0/1)                                                   
⠙ Preparing packages... (0/1)----     0 B/51.10 MiB                     
⠙ Preparing packages... (0/1)---- 16.00 KiB/51.10 MiB                   
⠙ Preparing packages... (0/1)---- 32.00 KiB/51.10 MiB                   
⠙ Preparing packages... (0/1)---- 48.00 KiB/51.10 MiB                   
⠙ Preparing packages... (0/1)---- 64.00 KiB/51.10 MiB                   
⠙ Preparing packages... (0/1)---- 80.00 KiB/51.10 MiB                   
⠙ Preparing packages... (0/1)---- 96.00 KiB/51.10 MiB                   
⠙ Preparing packages... (0/1)---- 112.00 KiB/51.10 MiB                  
⠙ Preparing packages... (0/1)---- 128.00 KiB/51.10 MiB                  
⠙ Preparing packages... (0/1)---- 144.00 KiB/51.10 MiB                  
⠙ Preparing packages... (0/1)---- 160.00 KiB/51.10 MiB                  
⠙ Pr

In [3]:
from transformers import AutoModelForCausalLM, AutoTokenizer
from datasets import load_dataset
import torch
import os

In [4]:
device =  "cuda"

In [5]:
model_name = "HuggingFaceTB/SmolLM2-135M-Instruct"
model = AutoModelForCausalLM.from_pretrained(pretrained_model_name_or_path=model_name).to(device)
tokenizer = AutoTokenizer.from_pretrained(pretrained_model_name_or_path=model_name)

config.json:   0%|          | 0.00/861 [00:00<?, ?B/s]

2025-05-07 16:19:54.992186: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1746634795.234016      31 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1746634795.309846      31 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


model.safetensors:   0%|          | 0.00/269M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/132 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/3.76k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/801k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/466k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.10M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/655 [00:00<?, ?B/s]

In [79]:
messages = [{"role": "user", "content": "What is the capital of france"}]
input_text=tokenizer.apply_chat_template(messages, tokenize=False)
print(input_text)
inputs = tokenizer.encode(input_text, return_tensors="pt").to(device)
outputs = model.generate(inputs, max_new_tokens=50, temperature=0.2, top_p=0.9, do_sample=True)
print(outputs)
out = tokenizer.decode(outputs[0])
print(out)

<|im_start|>system
You are a helpful AI assistant named SmolLM, trained by Hugging Face<|im_end|>
<|im_start|>user
What is the capital of france<|im_end|>

tensor([[    1,  9690,   198,  2683,   359,   253,  5356,  5646, 11173,  3365,
          3511,   308, 34519,    28,  7018,   411,   407, 19712,  8182,     2,
           198,     1,  4093,   198,  1780,   314,   260,  3575,   282,   275,
          8603,     2,   198,     1,   520,  9531,   198,   504,  3575,   282,
          4649,   314,  7042,    30,  7042,   314,   253,  2240,  1343,   327,
           624,  2844, 22387,    28,  2517,    28,   284, 13964,    30,   657,
           506,   253,  2378, 16477, 10420,   284,   253,  1739,  3113,  2240,
            30,   198,   198, 38634,   314,   597,   260,  3995,  2240,   281,
          4649,   284,   260]], device='cuda:0')
<|im_start|>system
You are a helpful AI assistant named SmolLM, trained by Hugging Face<|im_end|>
<|im_start|>user
What is the capital of france<|im_end|>
<|im_sta

In [8]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer, HfArgumentParser

In [9]:
reward_model = AutoModelForSequenceClassification.from_pretrained('trl-lib/Qwen2-0.5B-Reward')
r_tok = AutoTokenizer.from_pretrained(
        'trl-lib/Qwen2-0.5B-Reward',  use_fast=True
    )


config.json:   0%|          | 0.00/822 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.98G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/80.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/367 [00:00<?, ?B/s]

In [33]:
r_embed = r_tok.encode(out, return_tensors="pt")
reward_model(r_embed)

SequenceClassifierOutputWithPast(loss=None, logits=tensor([[-3.0947]], grad_fn=<IndexBackward0>), past_key_values=<transformers.cache_utils.DynamicCache object at 0x7b50f3a9b810>, hidden_states=None, attentions=None)

In [14]:
ds = load_dataset("HuggingFaceTB/smoltalk",'everyday-conversations')

README.md:   0%|          | 0.00/9.72k [00:00<?, ?B/s]

data/everyday-conversations/train-00000-(…):   0%|          | 0.00/946k [00:00<?, ?B/s]

data/everyday-conversations/test-00000-o(…):   0%|          | 0.00/52.6k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/2260 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/119 [00:00<?, ? examples/s]

In [17]:
ds['train'][0]['messages']

[{'content': 'Hi there', 'role': 'user'},
 {'content': 'Hello! How can I help you today?', 'role': 'assistant'},
 {'content': "I'm looking for a beach resort for my next vacation. Can you recommend some popular ones?",
  'role': 'user'},
 {'content': "Some popular beach resorts include Maui in Hawaii, the Maldives, and the Bahamas. They're known for their beautiful beaches and crystal-clear waters.",
  'role': 'assistant'},
 {'content': 'That sounds great. Are there any resorts in the Caribbean that are good for families?',
  'role': 'user'},
 {'content': 'Yes, the Turks and Caicos Islands and Barbados are excellent choices for family-friendly resorts in the Caribbean. They offer a range of activities and amenities suitable for all ages.',
  'role': 'assistant'},
 {'content': "Okay, I'll look into those. Thanks for the recommendations!",
  'role': 'user'},
 {'content': "You're welcome. I hope you find the perfect resort for your vacation.",
  'role': 'assistant'}]

In [18]:
tokenizer.apply_chat_template(ds['train'][0]['messages'], tokenize = False)

"<|im_start|>system\nYou are a helpful AI assistant named SmolLM, trained by Hugging Face<|im_end|>\n<|im_start|>user\nHi there<|im_end|>\n<|im_start|>assistant\nHello! How can I help you today?<|im_end|>\n<|im_start|>user\nI'm looking for a beach resort for my next vacation. Can you recommend some popular ones?<|im_end|>\n<|im_start|>assistant\nSome popular beach resorts include Maui in Hawaii, the Maldives, and the Bahamas. They're known for their beautiful beaches and crystal-clear waters.<|im_end|>\n<|im_start|>user\nThat sounds great. Are there any resorts in the Caribbean that are good for families?<|im_end|>\n<|im_start|>assistant\nYes, the Turks and Caicos Islands and Barbados are excellent choices for family-friendly resorts in the Caribbean. They offer a range of activities and amenities suitable for all ages.<|im_end|>\n<|im_start|>user\nOkay, I'll look into those. Thanks for the recommendations!<|im_end|>\n<|im_start|>assistant\nYou're welcome. I hope you find the perfect r

In [15]:
def tokenize_function(examples):
    texts = tokenizer.apply_chat_template(
            examples['messages'],
            tokenize=False
        )
    return tokenizer(texts, truncation=True, padding= False, max_length=512)


In [16]:
tok_ds = ds.map(tokenize_function, batched=True)

Map:   0%|          | 0/2260 [00:00<?, ? examples/s]

Map:   0%|          | 0/119 [00:00<?, ? examples/s]

In [17]:
from transformers import DataCollatorForLanguageModeling
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm= False)

In [18]:
tok_ds

DatasetDict({
    train: Dataset({
        features: ['full_topic', 'messages', 'input_ids', 'attention_mask'],
        num_rows: 2260
    })
    test: Dataset({
        features: ['full_topic', 'messages', 'input_ids', 'attention_mask'],
        num_rows: 119
    })
})

In [21]:
tok_ds =tok_ds.remove_columns(["full_topic", "messages"])

ValueError: Column name ['full_topic', 'messages'] not in the dataset. Current columns in the dataset: ['input_ids', 'attention_mask']

In [22]:
tok_ds.set_format("torch")

In [23]:
from torch.utils.data import DataLoader

train_dataloader = DataLoader(
    tok_ds["train"], shuffle=True, batch_size=8, collate_fn=data_collator
)

In [24]:
for batch in train_dataloader:
    break
{k: v.shape for k, v in batch.items()}


{'input_ids': torch.Size([8, 270]),
 'attention_mask': torch.Size([8, 270]),
 'labels': torch.Size([8, 270])}

In [25]:
len(batch['input_ids'][0])

270

In [26]:
batch.to(device)

{'input_ids': tensor([[   1, 9690,  198,  ...,    2,    2,    2],
        [   1, 9690,  198,  ...,    2,    2,    2],
        [   1, 9690,  198,  ...,    2,    2,    2],
        ...,
        [   1, 9690,  198,  ...,    2,    2,    2],
        [   1, 9690,  198,  ...,    2,    2,    2],
        [   1, 9690,  198,  ...,    2,    2,    2]], device='cuda:0'), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]], device='cuda:0'), 'labels': tensor([[   1, 9690,  198,  ..., -100, -100, -100],
        [   1, 9690,  198,  ..., -100, -100, -100],
        [   1, 9690,  198,  ..., -100, -100, -100],
        ...,
        [   1, 9690,  198,  ..., -100, -100, -100],
        [   1, 9690,  198,  ..., -100, -100, -100],
        [   1, 9690,  198,  ..., -100, -100, -100]], device='cuda:0')}

In [27]:
outputs = model(**batch)


In [28]:
tex_out = model.generate(**batch)
tokenizer.decode(tex_out[0])

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


"<|im_start|>system\nYou are a helpful AI assistant named SmolLM, trained by Hugging Face<|im_end|>\n<|im_start|>user\nHi<|im_end|>\n<|im_start|>assistant\nHello! How can I help you today?<|im_end|>\n<|im_start|>user\nI'm planning a family vacation. Do you have any ideas?<|im_end|>\n<|im_start|>assistant\nYes, I can suggest some popular family vacation spots. Have you considered going to the beach or a theme park?<|im_end|>\n<|im_start|>user\nThat sounds great. What are some good theme parks for families with young kids?<|im_end|>\n<|im_start|>assistant\nSome popular options include Disneyland, Legoland, and Universal Studios. They have rides and attractions suitable for young children.<|im_end|>\n<|im_start|>user\nThat's helpful, thank you.<|im_end|>\n<|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_en

In [61]:
outputs.loss

tensor(1.4384, device='cuda:0', grad_fn=<NllLossBackward0>)

In [62]:
outputs.logits[0].shape

torch.Size([270, 49152])

In [30]:
from torch.optim import AdamW

optimizer = AdamW(model.parameters(), lr=5e-5)

In [65]:
output_text = model.generate(**batch)

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


In [68]:
tokenizer.decode(output_text[0])

"<|im_start|>system\nYou are a helpful AI assistant named SmolLM, trained by Hugging Face<|im_end|>\n<|im_start|>user\nHi<|im_end|>\n<|im_start|>assistant\nHello! How can I help you today?<|im_end|>\n<|im_start|>user\nI'm planning a family vacation. Do you have any ideas?<|im_end|>\n<|im_start|>assistant\nYes, I can suggest some popular family vacation spots. Have you considered going to the beach or a theme park?<|im_end|>\n<|im_start|>user\nThat sounds great. What are some good theme parks for families with young kids?<|im_end|>\n<|im_start|>assistant\nSome popular options include Disneyland, Legoland, and Universal Studios. They have rides and attractions suitable for young children.<|im_end|>\n<|im_start|>user\nThat's helpful, thank you.<|im_end|>\n<|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_en

In [31]:
from transformers import get_scheduler

num_epochs = 3
num_training_steps = num_epochs * len(train_dataloader)
lr_scheduler = get_scheduler(
    "linear",
    optimizer=optimizer,
    num_warmup_steps=0,
    num_training_steps=num_training_steps,
)
print(num_training_steps)

849


In [32]:
model.train()

LlamaForCausalLM(
  (model): LlamaModel(
    (embed_tokens): Embedding(49152, 576, padding_idx=2)
    (layers): ModuleList(
      (0-29): 30 x LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear(in_features=576, out_features=576, bias=False)
          (k_proj): Linear(in_features=576, out_features=192, bias=False)
          (v_proj): Linear(in_features=576, out_features=192, bias=False)
          (o_proj): Linear(in_features=576, out_features=576, bias=False)
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=576, out_features=1536, bias=False)
          (up_proj): Linear(in_features=576, out_features=1536, bias=False)
          (down_proj): Linear(in_features=1536, out_features=576, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm((576,), eps=1e-05)
        (post_attention_layernorm): LlamaRMSNorm((576,), eps=1e-05)
      )
    )
    (norm): LlamaRMSNorm((576,), eps=1e-05)
    (rotary_emb)

In [51]:
def reward(r_embed, reward_model, out ):
    r_embed = r_tok.encode(out, return_tensors="pt")
    reward = reward_model(r_embed)
    reward = reward.logits.detach()
    return reward.squeeze(-1)
    

In [69]:
r = reward(r_embed,reward_model, tokenizer.decode(output_text[0]) )

In [74]:
r.to(0)

tensor([-4.0253], device='cuda:0')

In [76]:
loss

NameError: name 'loss' is not defined

In [ ]:
from tqdm.auto import tqdm
import torch

# Assuming model, train_dataloader, optimizer, lr_scheduler, device, num_epochs, lamda are defined

num_training_steps = len(train_dataloader) * num_epochs
progress_bar = tqdm(range(num_training_steps))

model.train()
for epoch in range(num_epochs):
    for batch in train_dataloader:
        batch = {k: v.to(device) for k, v in batch.items()}
        outputs = model(**batch)
        output_text = model.generate(**batch)

        r = reward(r_embed,reward_model, tokenizer.decode(output_text[0]) ).to(0)

        loss = outputs.loss - r
        loss.backward()  
        print(loss)

        optimizer.step()
        lr_scheduler.step()
        optimizer.zero_grad()
        progress_bar.update(1)

  0%|          | 0/849 [00:00<?, ?it/s]

A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([13.6270], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([6.1645], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([1.6646], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([5.7358], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.1942], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.6650], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([2.8062], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([7.3512], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([6.1434], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.4082], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.4645], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([6.1021], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.2931], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([9.6784], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.8063], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([-3.4224], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.2820], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([5.8228], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([0.5650], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.1654], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([2.1691], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.2604], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.6777], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.7680], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.6319], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([1.1698], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([5.5437], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.2864], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.7404], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([0.3636], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.2267], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([6.8913], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([-6.3155], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([1.8392], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([8.6982], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([-1.9456], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.7603], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.4112], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.8650], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([5.4548], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([-1.5186], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.4376], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([1.2292], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.6474], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.2479], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.9858], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([1.2586], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([5.4937], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([0.2192], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([-1.2982], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.4755], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([6.3247], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([5.1013], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([5.6240], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([6.8994], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.7646], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.0844], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([0.6188], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([0.5455], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([-0.4760], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([2.1200], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.1964], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([-2.8453], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([-1.2143], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.7317], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.7037], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([-2.0956], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([-3.9331], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.8615], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([10.2668], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.6745], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([6.3729], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([6.3257], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.6157], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.1976], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.8076], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([-0.2230], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.6997], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([-1.0870], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.4366], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.3400], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.4937], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([6.4047], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([-4.6662], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.4788], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([6.5685], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([5.5219], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.0963], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.9168], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([5.9480], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.8287], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.6237], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([6.0362], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([12.2641], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([5.3400], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.3527], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([-3.3963], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([5.4782], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.0170], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.5368], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([6.9645], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([5.1960], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([5.5292], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([5.9907], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([5.6468], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.1036], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([-0.6549], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([6.6759], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([0.2084], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([6.7855], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.2319], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([6.7889], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([5.3278], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([5.5074], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([7.2256], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([5.2302], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([6.0826], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.7097], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.3822], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.1834], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([2.8293], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([1.3047], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([5.7651], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([5.7084], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([6.2799], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.9192], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([2.3424], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.1885], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([6.2273], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.8508], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.8766], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([-2.0161], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([2.0621], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([1.0022], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.6270], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([1.1331], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.8277], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([1.7286], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.6234], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([2.8069], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([5.0424], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([2.8438], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.8339], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.2029], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([7.6062], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.7908], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([7.5098], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.0894], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([7.1249], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.3798], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([6.3082], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([1.9765], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.8632], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([0.8656], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([6.3258], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.8420], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([7.1717], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([6.2890], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([-0.2123], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.7785], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([5.6966], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.4620], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.0878], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.6207], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.0494], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([2.3326], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([5.4106], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.6246], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([12.4373], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.6242], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([1.7631], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([6.9403], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.9775], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([2.8066], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.4312], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([1.8036], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.7701], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([6.0008], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([5.6206], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([-0.1514], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.4615], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([7.6614], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([5.4977], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([5.5463], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.6921], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.4423], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([5.2349], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([7.9328], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.6654], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([1.9326], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([5.9953], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.5415], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([6.8634], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([5.8281], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([-1.7905], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.7574], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.5686], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([9.6847], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([7.1324], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.8497], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.8371], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([6.6011], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.8028], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.8586], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.3547], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([1.2131], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([7.3857], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.5576], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.9996], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([1.3316], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.7973], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.5838], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.9734], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([6.3068], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([0.1976], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.3744], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.9862], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([-0.2784], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([8.1159], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.4908], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.6908], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([1.7324], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.1023], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.4859], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([-2.3211], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([5.9415], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.3554], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([8.1958], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([7.6864], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([2.1916], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.0330], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.0177], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.4918], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.7910], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([6.7326], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([6.8515], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([8.3309], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([4.7518], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


tensor([3.5064], device='cuda:0', grad_fn=<SubBackward0>)


A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


In [115]:
import gc
gc.collect()
torch.cuda.empty_cache()